CREATE TABLE video
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version            INTEGER,
    title              VARCHAR,
    date               VARCHAR,
    start              VARCHAR,
    duration           VARCHAR,
    link               VARCHAR,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_video PRIMARY KEY (id)
);